# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: influxdb:1.8
    restart: always
    environment:
      INFLUXDB_DB: defaultdb
      INFLUXDB_ADMIN_USER: admin

  ui:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  ping:
    image: ping
    restart: always